name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-to-app-engine:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v1"
